#gb.api:
#  endpoint:
#    manufacturer-url: 'http://localhost:8080/api/v1/manufacturer'
#  connection:
#    period: 100
#    max-period: 10000 #Millis
#    max-attempts: 3
#    connect-timeout: 10000 #Millis
#    #    connect-timeout-unit:
#    read-timeout: 30000 #Millis
#    #    read-timeout-unit:
#    follow-redirects: true
server:
  port: 8081
  servlet:
    context-path: '/external'
spring:
  profiles:
    active: ${SPRING_PROFILES_INCLUDE:dev}
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://127.0.0.1:8888}
  cloud:
    config:
      label: ${SPRING_CLOUD_CONFIG_LEVEL:master}
      username: ${SPRING_CLOUD_CONFIG_USERNAME:geek_user}
      password: ${SPRING_CLOUD_CONFIG_PASSWORD:geek_pass}
#  datasource:
#    url: "jdbc:postgresql://localhost:5432/gb_shop"
#    username: "geek"
#    password: "geek"+